apiVersion: v1
kind: Pod
metadata:
  name: cmpod
spec:
  containers:
    - name: test-container
      image: nginx
      env:
        # Define the environment variable
        - name: ANYURL
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: myconfigmap
              # Specify the key associated with the value
              key: mydburl
        - name: MYUSERNAME
          valueFrom:
            secretKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: mysecret
              # Specify the key associated with the value
              key: username
        - name: MYPASSWORD
          valueFrom:
            secretKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: mysecret
              # Specify the key associated with the value
              key: password
  restartPolicy: Never
